version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "01:20"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "01:30"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 5
    groups:
      npm-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels:
      - dependencies

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "01:40"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 5
    groups:
      python-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels:
      - dependencies
