import { useEffect, useState } from "react";
import { BookOpen, Database, Loader2, MapPin, Plus, RotateCw, Sparkles, Users } from "lucide-react";
import type { UserRole } from "../types";
import { apiJson } from "../lib/apiClient";
import { Button, EmptyState, ErrorState, PageHeader, SectionCard, StatusBadge } from "./ui";

type Props = { role: UserRole };
type Article = { id: string; title: string; summary?: string | null; category: string; audience: string; status: string; version: number };
type Champion = { id: string; user_id: string; skills?: string[]; support_schedule?: string | null; supported_groups?: string | null; is_active: boolean };
type SupportPoint = { id: string; name: string; address: string; opening_hours?: string | null; equipment?: string[]; champion_id?: string | null };
type Scenario = { id: string; name: string; description?: string | null; status: string };
type Officer = { id: string; name: string; role: string; is_active: boolean };

const categoryLabels: Record<string, string> = { procedure: "Quy trình", guidance: "Hướng dẫn", lesson_learned: "Bài học kinh nghiệm", faq: "Hỏi đáp", policy: "Chính sách" };

export default function KnowledgeCenter({ role }: Props) {
  const admin = role === "admin_xa";
  const [articles, setArticles] = useState<Article[]>([]), [champions, setChampions] = useState<Champion[]>([]), [points, setPoints] = useState<SupportPoint[]>([]), [scenarios, setScenarios] = useState<Scenario[]>([]), [officers, setOfficers] = useState<Officer[]>([]);
  const [loading, setLoading] = useState(true), [error, setError] = useState<string | null>(null), [notice, setNotice] = useState<string | null>(null);
  const [articleTitle, setArticleTitle] = useState(""), [articleBody, setArticleBody] = useState("");
  const [pointName, setPointName] = useState(""), [pointAddress, setPointAddress] = useState(""), [pointHours, setPointHours] = useState(""), [pointEquipment, setPointEquipment] = useState(""), [pointChampionId, setPointChampionId] = useState("");
  const [championUserId, setChampionUserId] = useState(""), [championSkills, setChampionSkills] = useState(""), [championSchedule, setChampionSchedule] = useState(""), [championGroups, setChampionGroups] = useState("");
  const [scenarioName, setScenarioName] = useState(""), [runningScenario, setRunningScenario] = useState<string | null>(null), [scenarioResult, setScenarioResult] = useState<Record<string, number> | null>(null);
  const [baselinePopulation, setBaselinePopulation] = useState("1000"), [baselineBudget, setBaselineBudget] = useState("100"), [baselineDemand, setBaselineDemand] = useState("100");
  const [populationChange, setPopulationChange] = useState("5"), [budgetChange, setBudgetChange] = useState("0"), [demandChange, setDemandChange] = useState("10");

  const refresh = async () => {
    setLoading(true); setError(null);
    const results = await Promise.allSettled([apiJson<Article[]>("/api/knowledge/articles"), apiJson<Champion[]>("/api/knowledge/champions"), apiJson<SupportPoint[]>("/api/knowledge/support-points"), apiJson<Scenario[]>("/api/knowledge/scenarios"), ...(admin ? [apiJson<Officer[]>("/auth/officers")] : [])]);
    const [a, c, p, s, o] = results;
    if (a.status === "fulfilled") setArticles(a.value); if (c.status === "fulfilled") setChampions(c.value); if (p.status === "fulfilled") setPoints(p.value); if (s.status === "fulfilled") setScenarios(s.value); if (o?.status === "fulfilled") setOfficers(o.value as Officer[]);
    if (results.every((r) => r.status === "rejected")) setError("Không tải được kho tri thức. Kiểm tra quyền truy cập hoặc kết nối rồi thử lại."); setLoading(false);
  };
  useEffect(() => { void refresh(); }, []);
  const createArticle = async () => { if (!articleTitle.trim() || !articleBody.trim()) return; await apiJson<Article>("/api/knowledge/articles", { method: "POST", body: JSON.stringify({ title: articleTitle.trim(), body: articleBody.trim(), category: "guidance", audience: "internal" }) }); setArticleTitle(""); setArticleBody(""); setNotice("Đã lưu bài viết ở trạng thái bản nháp; cần admin duyệt trước khi dùng cho chatbot."); await refresh(); };
  const approveArticle = async (id: string) => { await apiJson<Article>(`/api/knowledge/articles/${id}/approve`, { method: "POST" }); setNotice("Đã duyệt tài liệu và ghi nhận người duyệt."); await refresh(); };
  const createPoint = async () => { if (!pointName.trim() || !pointAddress.trim()) return; await apiJson<SupportPoint>("/api/knowledge/support-points", { method: "POST", body: JSON.stringify({ name: pointName.trim(), address: pointAddress.trim(), opening_hours: pointHours.trim() || null, equipment: pointEquipment.split(",").map((x) => x.trim()).filter(Boolean), champion_id: pointChampionId || null }) }); setPointName(""); setPointAddress(""); setPointHours(""); setPointEquipment(""); setPointChampionId(""); setNotice("Đã thêm điểm hỗ trợ cộng đồng."); await refresh(); };
  const createChampion = async () => { if (!championUserId) return; await apiJson<Champion>("/api/knowledge/champions", { method: "POST", body: JSON.stringify({ user_id: championUserId, skills: championSkills.split(",").map((x) => x.trim()).filter(Boolean), support_schedule: championSchedule.trim() || null, supported_groups: championGroups.trim() || null }) }); setChampionUserId(""); setChampionSkills(""); setChampionSchedule(""); setChampionGroups(""); setNotice("Đã thêm Digital Champion và ghi nhận người phụ trách."); await refresh(); };
  const createScenario = async () => { if (!scenarioName.trim()) return; await apiJson<Scenario>("/api/knowledge/scenarios", { method: "POST", body: JSON.stringify({ name: scenarioName.trim() }) }); setScenarioName(""); setNotice("Đã tạo kịch bản. Kết quả mô phỏng không ghi ngược vào dữ liệu thật."); await refresh(); };
  const runScenario = async (id: string) => { setRunningScenario(id); setScenarioResult(null); try { const values = [baselinePopulation, baselineBudget, baselineDemand, populationChange, budgetChange, demandChange].map(Number); if (values.some((x) => !Number.isFinite(x) || x < 0)) throw new Error("Giá trị mô phỏng phải là số không âm."); const [population, budget, service_demand, population_change_pct, budget_change_pct, service_demand_change_pct] = values; const response = await apiJson<{ result?: { projection?: Record<string, number> } }>(`/api/knowledge/scenarios/${id}/run`, { method: "POST", body: JSON.stringify({ baseline: { population, budget, service_demand }, assumptions: { population_change_pct, budget_change_pct, service_demand_change_pct } }) }); setScenarioResult(response.result?.projection || null); setNotice("Đã chạy mô phỏng xác định. Đây là kết quả tham khảo, không phải dự báo AI."); } catch (e) { setNotice(e instanceof Error ? e.message : "Không thể chạy mô phỏng."); } finally { setRunningScenario(null); } };
  if (loading) return <div role="status" className="flex min-h-64 items-center justify-center gap-2 text-sm text-slate-600"><Loader2 className="h-5 w-5 animate-spin text-emerald-800" />Đang tải kho tri thức…</div>;
  if (error) return <ErrorState description={error} onRetry={() => void refresh()} />;
  return <div className="knowledge-page space-y-5"><PageHeader eyebrow="NĂNG LỰC & TRI THỨC" title="Kho tri thức và mô phỏng" description="Tài liệu đã duyệt, mạng lưới hỗ trợ số và kịch bản what-if cho xã Bà Nà." actions={<Button variant="secondary" onClick={() => void refresh()}><RotateCw />Làm mới</Button>} />{notice && <div role="status" className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-900">{notice}</div>}
    <SectionCard className="knowledge-section knowledge-section--articles"><div className="knowledge-section__header"><span className="knowledge-section__icon knowledge-section__icon--book"><BookOpen /></span><div><h2>Tài liệu nghiệp vụ</h2><p>Chatbot nội bộ chỉ dùng nội dung có nguồn và phiên bản.</p></div><span className="knowledge-section__count">{articles.length} tài liệu</span></div><div className="mt-4 space-y-2">{articles.length ? articles.map((article) => <article key={article.id} className="rounded-lg border border-slate-200 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-semibold">{article.title}</h3><p className="text-xs text-slate-500">{categoryLabels[article.category] || article.category} · phiên bản {article.version}</p></div><div className="flex items-center gap-2"><StatusBadge status={article.status} />{admin && article.status !== "approved" && <Button size="sm" onClick={() => void approveArticle(article.id)}>Duyệt</Button>}</div></div><p className="mt-1 text-sm text-slate-600">{article.summary || "Chưa có tóm tắt"}</p></article>) : <EmptyState title="Chưa có bài viết" description="Admin có thể tạo bản nháp rồi duyệt sau khi rà soát nội dung." />}</div>{admin && <div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-sm font-semibold">Tiêu đề<input className="mt-1 w-full" value={articleTitle} onChange={(e) => setArticleTitle(e.target.value)} placeholder="Ví dụ: Quy trình tiếp nhận phản ánh" /></label><label className="text-sm font-semibold md:row-span-2">Nội dung<textarea className="mt-1 min-h-24 w-full" value={articleBody} onChange={(e) => setArticleBody(e.target.value)} placeholder="Nội dung đã được kiểm duyệt nội bộ" /></label><div className="flex items-end"><Button onClick={() => void createArticle()} disabled={!articleTitle.trim() || !articleBody.trim()}><Plus />Tạo bản nháp</Button></div></div>}</SectionCard>
    <div className="grid gap-5 lg:grid-cols-2"><SectionCard className="knowledge-section knowledge-section--champions"><div className="knowledge-section__header"><span className="knowledge-section__icon knowledge-section__icon--people"><Users /></span><div><h2>Digital Champions</h2><p>Cán bộ hỗ trợ người dân và nhóm yếu thế.</p></div><span className="knowledge-section__count">{champions.length} người</span></div>{champions.length ? <ul className="knowledge-list mt-4">{champions.map((x) => <li key={x.id} className="knowledge-item"><strong>{officers.find((o) => o.id === x.user_id)?.name || x.user_id}</strong><span>Kỹ năng: {x.skills?.join(", ") || "Chưa cập nhật"}</span><span>Lịch hỗ trợ: {x.support_schedule || "Chưa cập nhật"}</span><span>Nhóm hỗ trợ: {x.supported_groups || "Chưa cập nhật"}</span></li>)}</ul> : <EmptyState title="Chưa có đại sứ số" description="Admin chọn cán bộ trong danh sách để phân công hỗ trợ." />}{admin && <div className="knowledge-form mt-4"><p className="knowledge-form__title">Thêm người phụ trách</p><select value={championUserId} onChange={(e) => setChampionUserId(e.target.value)}><option value="">Chọn cán bộ phụ trách</option>{officers.filter((o) => o.is_active && !champions.some((x) => x.user_id === o.id)).map((o) => <option key={o.id} value={o.id}>{o.name || o.id} · {o.role === "to_cnscd" ? "Tổ CNSCĐ" : "Cán bộ thôn"}</option>)}</select><input value={championSkills} onChange={(e) => setChampionSkills(e.target.value)} placeholder="Kỹ năng, phân cách bằng dấu phẩy" /><input value={championGroups} onChange={(e) => setChampionGroups(e.target.value)} placeholder="Nhóm hỗ trợ (người cao tuổi, hộ khó khăn…)" /><div className="flex gap-2"><input className="min-w-0 flex-1" value={championSchedule} onChange={(e) => setChampionSchedule(e.target.value)} placeholder="Lịch hỗ trợ" /><Button onClick={() => void createChampion()} disabled={!championUserId}><Plus />Thêm Champion</Button></div></div>}</SectionCard>
      <SectionCard className="knowledge-section knowledge-section--points"><div className="knowledge-section__header"><span className="knowledge-section__icon knowledge-section__icon--location"><MapPin /></span><div><h2>Điểm hỗ trợ cộng đồng</h2><p>Địa điểm, lịch trực và thiết bị dùng chung.</p></div><span className="knowledge-section__count">{points.length} điểm</span></div>{points.length ? <ul className="knowledge-list mt-4">{points.map((x) => <li key={x.id} className="knowledge-item"><strong>{x.name}</strong><span>{x.address}</span><span>{x.opening_hours || "Chưa cập nhật lịch"}</span><span>Thiết bị: {x.equipment?.join(", ") || "Chưa cập nhật"}</span></li>)}</ul> : <EmptyState title="Chưa có điểm hỗ trợ" description="Admin cấu hình địa điểm và thiết bị dùng chung." />}{admin && <div className="knowledge-form mt-4"><p className="knowledge-form__title">Thêm điểm hỗ trợ</p><input value={pointName} onChange={(e) => setPointName(e.target.value)} placeholder="Tên điểm hỗ trợ" /><input value={pointAddress} onChange={(e) => setPointAddress(e.target.value)} placeholder="Địa chỉ" /><input value={pointEquipment} onChange={(e) => setPointEquipment(e.target.value)} placeholder="Thiết bị (máy tính, máy quét…), phân cách bằng dấu phẩy" /><div className="flex gap-2"><input className="min-w-0 flex-1" value={pointHours} onChange={(e) => setPointHours(e.target.value)} placeholder="Lịch trực (ví dụ: T2–T6, 8:00–17:00)" /><select value={pointChampionId} onChange={(e) => setPointChampionId(e.target.value)}><option value="">Chọn người phụ trách</option>{champions.map((x) => <option key={x.id} value={x.id}>{officers.find((o) => o.id === x.user_id)?.name || x.user_id}</option>)}</select><Button onClick={() => void createPoint()} disabled={!pointName.trim() || !pointAddress.trim()}><Plus />Thêm điểm</Button></div></div>}</SectionCard></div>
    <SectionCard className="knowledge-section knowledge-section--scenarios"><div className="knowledge-section__header"><span className="knowledge-section__icon knowledge-section__icon--scenario"><Database /></span><div><h2>Mô phỏng what-if</h2><p>Tính toán xác định từ baseline; không phải dự báo AI và không sửa dữ liệu thật.</p></div><span className="knowledge-section__count">{scenarios.length} kịch bản</span></div>{scenarios.length ? <div className="knowledge-list mt-4">{scenarios.map((x) => <div key={x.id} className="knowledge-item knowledge-item--row"><div><strong>{x.name}</strong><span>{x.description || "Chưa có mô tả"}</span></div>{admin && <Button onClick={() => void runScenario(x.id)} disabled={runningScenario === x.id}>{runningScenario === x.id ? <Loader2 className="animate-spin" /> : <Sparkles />}Chạy mô phỏng</Button>}</div>)}</div> : <EmptyState title="Chưa có kịch bản" description="Tạo kịch bản để thử các giả định dân số, ngân sách và nhu cầu dịch vụ." />}{scenarioResult && <div role="status" className="knowledge-result mt-3"><strong>Kết quả mô phỏng:</strong> {Object.entries(scenarioResult).map(([key, value]) => `${key}: ${value}`).join(" · ")}</div>}{admin && <div className="knowledge-form mt-4"><p className="knowledge-form__title">Baseline và giả định (%)</p><div className="grid gap-2 sm:grid-cols-3"><input type="number" min="0" value={baselinePopulation} onChange={(e) => setBaselinePopulation(e.target.value)} placeholder="Dân số baseline" /><input type="number" min="0" value={baselineBudget} onChange={(e) => setBaselineBudget(e.target.value)} placeholder="Ngân sách baseline" /><input type="number" min="0" value={baselineDemand} onChange={(e) => setBaselineDemand(e.target.value)} placeholder="Nhu cầu baseline" /><input type="number" min="0" value={populationChange} onChange={(e) => setPopulationChange(e.target.value)} placeholder="% dân số" /><input type="number" min="0" value={budgetChange} onChange={(e) => setBudgetChange(e.target.value)} placeholder="% ngân sách" /><input type="number" min="0" value={demandChange} onChange={(e) => setDemandChange(e.target.value)} placeholder="% nhu cầu" /></div><div className="mt-3 flex gap-3"><input className="min-w-0 flex-1" value={scenarioName} onChange={(e) => setScenarioName(e.target.value)} placeholder="Tên kịch bản, ví dụ: Tăng nhu cầu dịch vụ 10%" /><Button onClick={() => void createScenario()} disabled={!scenarioName.trim()}><Plus />Tạo kịch bản</Button></div></div>}</SectionCard>
  </div>;
}
