import { useEffect, useState } from "react";
import { BookOpen, Database, Loader2, MapPin, Plus, RotateCw, Sparkles, Users } from "lucide-react";
import type { UserRole } from "../types";
import { apiJson } from "../lib/apiClient";
import { loadVillages } from "../lib/useVillages";
import { Button, EmptyState, ErrorState, PageHeader, SectionCard, StatusBadge } from "./ui";

type Props = { role: UserRole };
type Article = { id: string; title: string; summary?: string | null; category: string; audience: string; status: string; version: number };
type Champion = { id: string; user_id: string; skills?: string[]; support_schedule?: string | null; supported_groups?: string | null; is_active: boolean };
type SupportPoint = { id: string; name: string; address: string; opening_hours?: string | null; equipment?: string[]; champion_id?: string | null };
type Scenario = { id: string; name: string; description?: string | null; status: string };
type Officer = { id: string; name: string; role: string; is_active: boolean };
type EvacuationPoint = { id: string; village_id: string; name: string; latitude: number; longitude: number; capacity_households: number; contact_name: string; contact_phone: string; is_verified: boolean };

const categoryLabels: Record<string, string> = { procedure: "Quy trÃ¬nh", guidance: "HÆ°á»›ng dáº«n", lesson_learned: "BÃ i há»c kinh nghiá»‡m", faq: "Há»i Ä‘Ã¡p", policy: "ChÃ­nh sÃ¡ch" };

export default function KnowledgeCenter({ role }: Props) {
  const admin = role === "admin_xa";
  const canViewEvacuation = admin || role === "lanh_dao";
  const [articles, setArticles] = useState<Article[]>([]), [champions, setChampions] = useState<Champion[]>([]), [points, setPoints] = useState<SupportPoint[]>([]), [scenarios, setScenarios] = useState<Scenario[]>([]), [officers, setOfficers] = useState<Officer[]>([]), [villages, setVillages] = useState<{ id: string; name: string }[]>([]), [evacuationPoints, setEvacuationPoints] = useState<EvacuationPoint[]>([]);
  const [loading, setLoading] = useState(true), [error, setError] = useState<string | null>(null), [notice, setNotice] = useState<string | null>(null);
  const [articleTitle, setArticleTitle] = useState(""), [articleBody, setArticleBody] = useState("");
  const [pointName, setPointName] = useState(""), [pointAddress, setPointAddress] = useState(""), [pointHours, setPointHours] = useState(""), [pointEquipment, setPointEquipment] = useState(""), [pointChampionId, setPointChampionId] = useState("");
  const [evacuationVillageId, setEvacuationVillageId] = useState(""), [evacuationName, setEvacuationName] = useState(""), [evacuationLatitude, setEvacuationLatitude] = useState(""), [evacuationLongitude, setEvacuationLongitude] = useState(""), [evacuationCapacity, setEvacuationCapacity] = useState(""), [evacuationContact, setEvacuationContact] = useState("Trá»±c ban UBND xÃ£"), [evacuationPhone, setEvacuationPhone] = useState("0000000000");
  const [championUserId, setChampionUserId] = useState(""), [championSkills, setChampionSkills] = useState(""), [championSchedule, setChampionSchedule] = useState(""), [championGroups, setChampionGroups] = useState("");
  const [scenarioName, setScenarioName] = useState(""), [runningScenario, setRunningScenario] = useState<string | null>(null), [scenarioResult, setScenarioResult] = useState<Record<string, number> | null>(null);
  const [baselinePopulation, setBaselinePopulation] = useState("1000"), [baselineBudget, setBaselineBudget] = useState("100"), [baselineDemand, setBaselineDemand] = useState("100");
  const [populationChange, setPopulationChange] = useState("5"), [budgetChange, setBudgetChange] = useState("0"), [demandChange, setDemandChange] = useState("10");

  const refresh = async () => {
    setLoading(true); setError(null);
    const results = await Promise.allSettled([apiJson<Article[]>("/api/knowledge/articles"), apiJson<Champion[]>("/api/knowledge/champions"), apiJson<SupportPoint[]>("/api/knowledge/support-points"), apiJson<Scenario[]>("/api/knowledge/scenarios"), ...(canViewEvacuation ? [apiJson<Officer[]>("/auth/officers"), loadVillages(), apiJson<EvacuationPoint[]>("/api/pilots/evacuation-points/admin")] : [])]);
    const [a, c, p, s, o] = results;
    if (a.status === "fulfilled") setArticles(a.value); if (c.status === "fulfilled") setChampions(c.value); if (p.status === "fulfilled") setPoints(p.value); if (s.status === "fulfilled") setScenarios(s.value); if (o?.status === "fulfilled") setOfficers(o.value as Officer[]); const v = results[5]; const e = results[6]; if (v?.status === "fulfilled") setVillages((v.value as { id: string; name: string }[]).map((x) => ({ id: x.id, name: x.name }))); if (e?.status === "fulfilled") setEvacuationPoints(e.value as EvacuationPoint[]);
    if (results.every((r) => r.status === "rejected")) setError("KhÃ´ng táº£i Ä‘Æ°á»£c kho tri thá»©c. Kiá»ƒm tra quyá»n truy cáº­p hoáº·c káº¿t ná»‘i rá»“i thá»­ láº¡i."); setLoading(false);
  };
  useEffect(() => { void refresh(); }, []);
  const createArticle = async () => { if (!articleTitle.trim() || !articleBody.trim()) return; await apiJson<Article>("/api/knowledge/articles", { method: "POST", body: JSON.stringify({ title: articleTitle.trim(), body: articleBody.trim(), category: "guidance", audience: "internal" }) }); setArticleTitle(""); setArticleBody(""); setNotice("ÄÃ£ lÆ°u bÃ i viáº¿t á»Ÿ tráº¡ng thÃ¡i báº£n nhÃ¡p; cáº§n admin duyá»‡t trÆ°á»›c khi dÃ¹ng cho chatbot."); await refresh(); };
  const approveArticle = async (id: string) => { await apiJson<Article>(`/api/knowledge/articles/${id}/approve`, { method: "POST" }); setNotice("ÄÃ£ duyá»‡t tÃ i liá»‡u vÃ  ghi nháº­n ngÆ°á»i duyá»‡t."); await refresh(); };
  const createPoint = async () => { if (!pointName.trim() || !pointAddress.trim()) return; await apiJson<SupportPoint>("/api/knowledge/support-points", { method: "POST", body: JSON.stringify({ name: pointName.trim(), address: pointAddress.trim(), opening_hours: pointHours.trim() || null, equipment: pointEquipment.split(",").map((x) => x.trim()).filter(Boolean), champion_id: pointChampionId || null }) }); setPointName(""); setPointAddress(""); setPointHours(""); setPointEquipment(""); setPointChampionId(""); setNotice("ÄÃ£ thÃªm Ä‘iá»ƒm há»— trá»£ cá»™ng Ä‘á»“ng."); await refresh(); };
  const createEvacuationPoint = async () => { const latitude = Number(evacuationLatitude), longitude = Number(evacuationLongitude), capacity = Number(evacuationCapacity); if (!evacuationVillageId || !evacuationName.trim() || !Number.isFinite(latitude) || !Number.isFinite(longitude) || !Number.isInteger(capacity) || capacity <= 0) return; await apiJson<EvacuationPoint>("/api/pilots/evacuation-points", { method: "POST", body: JSON.stringify({ village_id: evacuationVillageId, name: evacuationName.trim(), latitude, longitude, capacity_households: capacity, contact_name: evacuationContact.trim() || "Trá»±c ban UBND xÃ£", contact_phone: evacuationPhone.trim() || "0000000000" }) }); setEvacuationName(""); setEvacuationLatitude(""); setEvacuationLongitude(""); setEvacuationCapacity(""); setNotice("ÄÃ£ thÃªm Ä‘iá»ƒm sÆ¡ tÃ¡n á»Ÿ tráº¡ng thÃ¡i chá» xÃ¡c minh."); await refresh(); };
  const toggleEvacuationPoint = async (point: EvacuationPoint) => { await apiJson<EvacuationPoint>(`/api/pilots/evacuation-points/${point.id}/verification`, { method: "PATCH", body: JSON.stringify({ is_verified: !point.is_verified }) }); setNotice(point.is_verified ? "ÄÃ£ áº©n Ä‘iá»ƒm sÆ¡ tÃ¡n khá»i cá»•ng cÃ´ng khai." : "ÄÃ£ xÃ¡c minh vÃ  cÃ´ng bá»‘ Ä‘iá»ƒm sÆ¡ tÃ¡n."); await refresh(); };
  const createChampion = async () => { if (!championUserId) return; await apiJson<Champion>("/api/knowledge/champions", { method: "POST", body: JSON.stringify({ user_id: championUserId, skills: championSkills.split(",").map((x) => x.trim()).filter(Boolean), support_schedule: championSchedule.trim() || null, supported_groups: championGroups.trim() || null }) }); setChampionUserId(""); setChampionSkills(""); setChampionSchedule(""); setChampionGroups(""); setNotice("ÄÃ£ thÃªm Digital Champion vÃ  ghi nháº­n ngÆ°á»i phá»¥ trÃ¡ch."); await refresh(); };
  const createScenario = async () => { if (!scenarioName.trim()) return; await apiJson<Scenario>("/api/knowledge/scenarios", { method: "POST", body: JSON.stringify({ name: scenarioName.trim() }) }); setScenarioName(""); setNotice("ÄÃ£ táº¡o ká»‹ch báº£n. Káº¿t quáº£ mÃ´ phá»ng khÃ´ng ghi ngÆ°á»£c vÃ o dá»¯ liá»‡u tháº­t."); await refresh(); };
  const runScenario = async (id: string) => { setRunningScenario(id); setScenarioResult(null); try { const values = [baselinePopulation, baselineBudget, baselineDemand, populationChange, budgetChange, demandChange].map(Number); if (values.some((x) => !Number.isFinite(x) || x < 0)) throw new Error("GiÃ¡ trá»‹ mÃ´ phá»ng pháº£i lÃ  sá»‘ khÃ´ng Ã¢m."); const [population, budget, service_demand, population_change_pct, budget_change_pct, service_demand_change_pct] = values; const response = await apiJson<{ result?: { projection?: Record<string, number> } }>(`/api/knowledge/scenarios/${id}/run`, { method: "POST", body: JSON.stringify({ baseline: { population, budget, service_demand }, assumptions: { population_change_pct, budget_change_pct, service_demand_change_pct } }) }); setScenarioResult(response.result?.projection || null); setNotice("ÄÃ£ cháº¡y mÃ´ phá»ng xÃ¡c Ä‘á»‹nh. ÄÃ¢y lÃ  káº¿t quáº£ tham kháº£o, khÃ´ng pháº£i dá»± bÃ¡o AI."); } catch (e) { setNotice(e instanceof Error ? e.message : "KhÃ´ng thá»ƒ cháº¡y mÃ´ phá»ng."); } finally { setRunningScenario(null); } };
  if (loading) return <div role="status" className="flex min-h-64 items-center justify-center gap-2 text-sm text-slate-600"><Loader2 className="h-5 w-5 animate-spin text-emerald-800" />Äang táº£i kho tri thá»©câ€¦</div>;
  if (error) return <ErrorState description={error} onRetry={() => void refresh()} />;
  return <div className="knowledge-page space-y-5"><PageHeader eyebrow="NÄ‚NG Lá»°C & TRI THá»¨C" title="Kho tri thá»©c vÃ  mÃ´ phá»ng" description="TÃ i liá»‡u Ä‘Ã£ duyá»‡t, máº¡ng lÆ°á»›i há»— trá»£ sá»‘ vÃ  ká»‹ch báº£n what-if cho xÃ£ BÃ  NÃ ." actions={<Button variant="secondary" onClick={() => void refresh()}><RotateCw />LÃ m má»›i</Button>} />{notice && <div role="status" className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-900">{notice}</div>}
    <SectionCard className="knowledge-section knowledge-section--articles"><div className="knowledge-section__header"><span className="knowledge-section__icon knowledge-section__icon--book"><BookOpen /></span><div><h2>TÃ i liá»‡u nghiá»‡p vá»¥</h2><p>Chatbot ná»™i bá»™ chá»‰ dÃ¹ng ná»™i dung cÃ³ nguá»“n vÃ  phiÃªn báº£n.</p></div><span className="knowledge-section__count">{articles.length} tÃ i liá»‡u</span></div><div className="mt-4 space-y-2">{articles.length ? articles.map((article) => <article key={article.id} className="rounded-lg border border-slate-200 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-semibold">{article.title}</h3><p className="text-xs text-slate-500">{categoryLabels[article.category] || article.category} Â· phiÃªn báº£n {article.version}</p></div><div className="flex items-center gap-2"><StatusBadge status={article.status} />{admin && article.status !== "approved" && <Button size="sm" onClick={() => void approveArticle(article.id)}>Duyá»‡t</Button>}</div></div><p className="mt-1 text-sm text-slate-600">{article.summary || "ChÆ°a cÃ³ tÃ³m táº¯t"}</p></article>) : <EmptyState title="ChÆ°a cÃ³ bÃ i viáº¿t" description="Admin cÃ³ thá»ƒ táº¡o báº£n nhÃ¡p rá»“i duyá»‡t sau khi rÃ  soÃ¡t ná»™i dung." />}</div>{admin && <div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-sm font-semibold">TiÃªu Ä‘á»<input className="mt-1 w-full" value={articleTitle} onChange={(e) => setArticleTitle(e.target.value)} placeholder="VÃ­ dá»¥: Quy trÃ¬nh tiáº¿p nháº­n pháº£n Ã¡nh" /></label><label className="text-sm font-semibold md:row-span-2">Ná»™i dung<textarea className="mt-1 min-h-24 w-full" value={articleBody} onChange={(e) => setArticleBody(e.target.value)} placeholder="Ná»™i dung Ä‘Ã£ Ä‘Æ°á»£c kiá»ƒm duyá»‡t ná»™i bá»™" /></label><div className="flex items-end"><Button onClick={() => void createArticle()} disabled={!articleTitle.trim() || !articleBody.trim()}><Plus />Táº¡o báº£n nhÃ¡p</Button></div></div>}</SectionCard>
    <div className="grid gap-5 lg:grid-cols-2"><SectionCard className="knowledge-section knowledge-section--champions"><div className="knowledge-section__header"><span className="knowledge-section__icon knowledge-section__icon--people"><Users /></span><div><h2>Digital Champions</h2><p>CÃ¡n bá»™ há»— trá»£ ngÆ°á»i dÃ¢n vÃ  nhÃ³m yáº¿u tháº¿.</p></div><span className="knowledge-section__count">{champions.length} ngÆ°á»i</span></div>{champions.length ? <ul className="knowledge-list mt-4">{champions.map((x) => <li key={x.id} className="knowledge-item"><strong>{officers.find((o) => o.id === x.user_id)?.name || x.user_id}</strong><span>Ká»¹ nÄƒng: {x.skills?.join(", ") || "ChÆ°a cáº­p nháº­t"}</span><span>Lá»‹ch há»— trá»£: {x.support_schedule || "ChÆ°a cáº­p nháº­t"}</span><span>NhÃ³m há»— trá»£: {x.supported_groups || "ChÆ°a cáº­p nháº­t"}</span></li>)}</ul> : <EmptyState title="ChÆ°a cÃ³ Ä‘áº¡i sá»© sá»‘" description="Admin chá»n cÃ¡n bá»™ trong danh sÃ¡ch Ä‘á»ƒ phÃ¢n cÃ´ng há»— trá»£." />}{admin && <div className="knowledge-form mt-4"><p className="knowledge-form__title">ThÃªm ngÆ°á»i phá»¥ trÃ¡ch</p><select value={championUserId} onChange={(e) => setChampionUserId(e.target.value)}><option value="">Chá»n cÃ¡n bá»™ phá»¥ trÃ¡ch</option>{officers.filter((o) => o.is_active && !champions.some((x) => x.user_id === o.id)).map((o) => <option key={o.id} value={o.id}>{o.name || o.id} Â· {o.role === "to_cnscd" ? "Tá»• CNSCÄ" : "CÃ¡n bá»™ thÃ´n"}</option>)}</select><input value={championSkills} onChange={(e) => setChampionSkills(e.target.value)} placeholder="Ká»¹ nÄƒng, phÃ¢n cÃ¡ch báº±ng dáº¥u pháº©y" /><input value={championGroups} onChange={(e) => setChampionGroups(e.target.value)} placeholder="NhÃ³m há»— trá»£ (ngÆ°á»i cao tuá»•i, há»™ khÃ³ khÄƒnâ€¦)" /><div className="flex gap-2"><input className="min-w-0 flex-1" value={championSchedule} onChange={(e) => setChampionSchedule(e.target.value)} placeholder="Lá»‹ch há»— trá»£" /><Button onClick={() => void createChampion()} disabled={!championUserId}><Plus />ThÃªm Champion</Button></div></div>}</SectionCard>
      <SectionCard className="knowledge-section knowledge-section--points"><div className="knowledge-section__header"><span className="knowledge-section__icon knowledge-section__icon--location"><MapPin /></span><div><h2>Äiá»ƒm há»— trá»£ cá»™ng Ä‘á»“ng</h2><p>Äá»‹a Ä‘iá»ƒm, lá»‹ch trá»±c vÃ  thiáº¿t bá»‹ dÃ¹ng chung.</p></div><span className="knowledge-section__count">{points.length} Ä‘iá»ƒm</span></div>{points.length ? <ul className="knowledge-list mt-4">{points.map((x) => <li key={x.id} className="knowledge-item"><strong>{x.name}</strong><span>{x.address}</span><span>{x.opening_hours || "ChÆ°a cáº­p nháº­t lá»‹ch"}</span><span>Thiáº¿t bá»‹: {x.equipment?.join(", ") || "ChÆ°a cáº­p nháº­t"}</span></li>)}</ul> : <EmptyState title="ChÆ°a cÃ³ Ä‘iá»ƒm há»— trá»£" description="Admin cáº¥u hÃ¬nh Ä‘á»‹a Ä‘iá»ƒm vÃ  thiáº¿t bá»‹ dÃ¹ng chung." />}{admin && <div className="knowledge-form mt-4"><p className="knowledge-form__title">ThÃªm Ä‘iá»ƒm há»— trá»£</p><input value={pointName} onChange={(e) => setPointName(e.target.value)} placeholder="TÃªn Ä‘iá»ƒm há»— trá»£" /><input value={pointAddress} onChange={(e) => setPointAddress(e.target.value)} placeholder="Äá»‹a chá»‰" /><input value={pointEquipment} onChange={(e) => setPointEquipment(e.target.value)} placeholder="Thiáº¿t bá»‹ (mÃ¡y tÃ­nh, mÃ¡y quÃ©tâ€¦), phÃ¢n cÃ¡ch báº±ng dáº¥u pháº©y" /><div className="flex gap-2"><input className="min-w-0 flex-1" value={pointHours} onChange={(e) => setPointHours(e.target.value)} placeholder="Lá»‹ch trá»±c (vÃ­ dá»¥: T2â€“T6, 8:00â€“17:00)" /><select value={pointChampionId} onChange={(e) => setPointChampionId(e.target.value)}><option value="">Chá»n ngÆ°á»i phá»¥ trÃ¡ch</option>{champions.map((x) => <option key={x.id} value={x.id}>{officers.find((o) => o.id === x.user_id)?.name || x.user_id}</option>)}</select><Button onClick={() => void createPoint()} disabled={!pointName.trim() || !pointAddress.trim()}><Plus />ThÃªm Ä‘iá»ƒm</Button></div></div>}</SectionCard></div>
    {canViewEvacuation && <SectionCard className="knowledge-section knowledge-section--evacuation"><div className="knowledge-section__header"><span className="knowledge-section__icon knowledge-section__icon--location"><MapPin /></span><div><h2>Điểm sơ tán</h2><p>Admin quản lý và xác minh; lãnh đạo xem xét. Chỉ điểm đã xác minh mới được công khai.</p></div><span className="knowledge-section__count">{evacuationPoints.length} điểm</span></div>{evacuationPoints.length ? <ul className="knowledge-list mt-4">{evacuationPoints.map((point) => <li key={point.id} className="knowledge-item"><strong>{point.name}</strong><span>{villages.find((v) => v.id === point.village_id)?.name || "Chưa xác định thôn"} · sức chứa {point.capacity_households.toLocaleString("vi-VN")} hộ</span><span>Tọa độ: {point.latitude}, {point.longitude}</span><StatusBadge status={point.is_verified ? "approved" : "draft"} label={point.is_verified ? "Đã công khai" : "Chờ xác minh"} />{admin && <Button size="sm" onClick={() => void toggleEvacuationPoint(point)}>{point.is_verified ? "Ẩn khỏi công khai" : "Xác minh & công khai"}</Button>}</li>)}</ul> : <EmptyState title="Chưa có điểm sơ tán" description="Admin thêm điểm sau khi có nguồn chính thức." />}{admin && <div className="knowledge-form mt-4"><p className="knowledge-form__title">Thêm điểm sơ tán (chờ xác minh)</p><div className="grid gap-2 sm:grid-cols-2"><select value={evacuationVillageId} onChange={(e) => setEvacuationVillageId(e.target.value)}><option value="">Chọn thôn</option>{villages.map((v) => <option key={v.id} value={v.id}>{v.name}</option>)}</select><input value={evacuationName} onChange={(e) => setEvacuationName(e.target.value)} placeholder="Tên điểm sơ tán" /><input type="number" min="-90" max="90" step="any" value={evacuationLatitude} onChange={(e) => setEvacuationLatitude(e.target.value)} placeholder="Vĩ độ" /><input type="number" min="-180" max="180" step="any" value={evacuationLongitude} onChange={(e) => setEvacuationLongitude(e.target.value)} placeholder="Kinh độ" /><input type="number" min="1" value={evacuationCapacity} onChange={(e) => setEvacuationCapacity(e.target.value)} placeholder="Sức chứa (hộ)" /><input value={evacuationContact} onChange={(e) => setEvacuationContact(e.target.value)} placeholder="Đầu mối nội bộ" /><input value={evacuationPhone} onChange={(e) => setEvacuationPhone(e.target.value)} placeholder="Số điện thoại nội bộ" /></div><p className="text-xs text-slate-500">Thông tin liên hệ chỉ dùng nội bộ; admin phải xác minh nguồn trước khi công khai.</p><Button onClick={() => void createEvacuationPoint()} disabled={!evacuationVillageId || !evacuationName.trim() || !evacuationLatitude || !evacuationLongitude || !evacuationCapacity}><Plus />Tạo điểm chờ xác minh</Button></div>}</SectionCard>}
    <SectionCard className="knowledge-section knowledge-section--scenarios"><div className="knowledge-section__header"><span className="knowledge-section__icon knowledge-section__icon--scenario"><Database /></span><div><h2>MÃ´ phá»ng what-if</h2><p>TÃ­nh toÃ¡n xÃ¡c Ä‘á»‹nh tá»« baseline; khÃ´ng pháº£i dá»± bÃ¡o AI vÃ  khÃ´ng sá»­a dá»¯ liá»‡u tháº­t.</p></div><span className="knowledge-section__count">{scenarios.length} ká»‹ch báº£n</span></div>{scenarios.length ? <div className="knowledge-list mt-4">{scenarios.map((x) => <div key={x.id} className="knowledge-item knowledge-item--row"><div><strong>{x.name}</strong><span>{x.description || "ChÆ°a cÃ³ mÃ´ táº£"}</span></div>{admin && <Button onClick={() => void runScenario(x.id)} disabled={runningScenario === x.id}>{runningScenario === x.id ? <Loader2 className="animate-spin" /> : <Sparkles />}Cháº¡y mÃ´ phá»ng</Button>}</div>)}</div> : <EmptyState title="ChÆ°a cÃ³ ká»‹ch báº£n" description="Táº¡o ká»‹ch báº£n Ä‘á»ƒ thá»­ cÃ¡c giáº£ Ä‘á»‹nh dÃ¢n sá»‘, ngÃ¢n sÃ¡ch vÃ  nhu cáº§u dá»‹ch vá»¥." />}{scenarioResult && <div role="status" className="knowledge-result mt-3"><strong>Káº¿t quáº£ mÃ´ phá»ng:</strong> {Object.entries(scenarioResult).map(([key, value]) => `${key}: ${value}`).join(" Â· ")}</div>}{admin && <div className="knowledge-form mt-4"><p className="knowledge-form__title">Baseline vÃ  giáº£ Ä‘á»‹nh (%)</p><div className="grid gap-2 sm:grid-cols-3"><input type="number" min="0" value={baselinePopulation} onChange={(e) => setBaselinePopulation(e.target.value)} placeholder="DÃ¢n sá»‘ baseline" /><input type="number" min="0" value={baselineBudget} onChange={(e) => setBaselineBudget(e.target.value)} placeholder="NgÃ¢n sÃ¡ch baseline" /><input type="number" min="0" value={baselineDemand} onChange={(e) => setBaselineDemand(e.target.value)} placeholder="Nhu cáº§u baseline" /><input type="number" min="0" value={populationChange} onChange={(e) => setPopulationChange(e.target.value)} placeholder="% dÃ¢n sá»‘" /><input type="number" min="0" value={budgetChange} onChange={(e) => setBudgetChange(e.target.value)} placeholder="% ngÃ¢n sÃ¡ch" /><input type="number" min="0" value={demandChange} onChange={(e) => setDemandChange(e.target.value)} placeholder="% nhu cáº§u" /></div><div className="mt-3 flex gap-3"><input className="min-w-0 flex-1" value={scenarioName} onChange={(e) => setScenarioName(e.target.value)} placeholder="TÃªn ká»‹ch báº£n, vÃ­ dá»¥: TÄƒng nhu cáº§u dá»‹ch vá»¥ 10%" /><Button onClick={() => void createScenario()} disabled={!scenarioName.trim()}><Plus />Táº¡o ká»‹ch báº£n</Button></div></div>}</SectionCard>
  </div>;
}
